[tool.poetry]
name = "joytalk"
version = "1.0.0"
description = "A bot for discord to convert text to speech"
authors = ["yusuken <yusuken_@acm.org>"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.8.3"
"discord.py" = ">=1.5.0"
PyNaCl = "^1.4.0"
google-cloud-texttospeech = "^2.2.0"
